services:
  - type: web
    name: stalk-the-stock
    env: python
    buildCommand: pip install -r requirements.txt | python manage.py collectstatic --noinput
    startCommand: gunicorn demostocks.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: demostocks.settings
      - key: PYTHON_VERSION
        value: 3.11
