services:
  - type: web
    name: stalk-the-stock
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn demostocks.wsgi:application --preload
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
